updated build script

diff --git a/bin/bashrc b/bin/bashrc
--- a/bin/bashrc
+++ b/bin/bashrc
@@ -131,6 +131,25 @@ alias cdoom="cd \"\${DOOMWADDIR}\""
 
 alias ffmpeg="ffmpeg -hide_banner"
 
+function doom-cmake-bare() {
+	dir_name=$(basename "${PWD}")
+	if [[ "${dir_name}" != "build" ]]; then
+		echo "Not inside \`build/\` dir. Aborting.";
+		return;
+	fi
+
+	cmake .. \
+		-DCMAKE_BUILD_TYPE=Release \
+		--fresh;
+
+	if [[ $? -eq 0 ]]; then
+		sudo make install -j$(nproc)
+	else
+		echo "CMake failed. Abort."
+		return 1
+	fi
+}
+
 function doom-cmake() {
 	dir_name=$(basename "${PWD}")
 	if [[ "${dir_name}" != "build" ]]; then
@@ -146,35 +165,35 @@ function doom-cmake() {
 		-DCMAKE_INTERPROCEDURAL_OPTIMIZATION=ON \
 		--fresh;
 
-    if [[ $? -eq 0 ]]; then
-        sudo make install -j$(nproc)
-    else
-        echo "CMake failed. Abort."
-        return 1
-    fi
+	if [[ $? -eq 0 ]]; then
+		sudo make install -j$(nproc)
+	else
+		echo "CMake failed. Abort."
+		return 1
+	fi
 }
 
 function play_midi() {
-	fluidsynth                       \
+	fluidsynth \
 		-ni "${SF2:-${DEFAULT_SF2}}" \
-		-r 44100                     \
+		-r 44100 \
 		"${1}"
 }
 
 function bulk_sf2_midi() {
 	for mid_file in *.mid; do
 		# simple render midi to wav
-		fluidsynth                       \
+		fluidsynth \
 			-ni "${SF2:-${DEFAULT_SF2}}" \
-			"${mid_file}"                \
-			-F "${mid_file%.mid}".wav    \
+			"${mid_file}"  \
+			-F "${mid_file%.mid}".wav \
 			-r 44100;
 		# convert wav to ogg
-		ffmpeg                        \
+		ffmpeg \
 			-i "${mid_file%.mid}".wav \
-			-b:a 64k                  \
-			-af "volume=10dB"         \
-			"${mid_file%.mid}".ogg    \
+			-b:a 64k \
+			-af "volume=10dB" \
+			"${mid_file%.mid}".ogg \
 			-y;
 		# clean up
 		rm "${mid_file%.mid}".wav;
@@ -186,37 +205,37 @@ function bulk_nuked_midi() {
 
 		# simple render midi to wav
 		! [[ -d "./wav" ]] && mkdir wav;
-		nuked-sc55-render                                 \
-			--romset mk2                                  \
+		nuked-sc55-render \
+			--romset mk2 \
 			--rom-directory "/usr/local/share/nuked-sc55" \
-			--reset gs"${mid_file%.mid}".wav              \
-			-o ./wav/"${mid_file%.mid}".wav               \
+			--reset gs"${mid_file%.mid}".wav \
+			-o ./wav/"${mid_file%.mid}".wav \
 			"${mid_file}";
 
 			# convert wav to flac
 		! [[ -d "./flac" ]] && mkdir flac;
-		ffmpeg                              \
+		ffmpeg \
 			-i ./wav/"${mid_file%.mid}".wav \
-			-ar 48000                       \
-			-af "volume=10dB"               \
-			./flac/"${mid_file%.mid}".flac  \
+			-ar 48000 \
+			-af "volume=10dB" \
+			./flac/"${mid_file%.mid}".flac \
 			-y;
 
 		# convert wav to mp3
 		! [[ -d "./mp3" ]] && mkdir mp3;
-		ffmpeg                              \
+		ffmpeg \
 			-i ./wav/"${mid_file%.mid}".wav \
-			-ar 44100                       \
-			-af "volume=10dB"               \
-			./mp3/"${mid_file%.mid}".mp3    \
+			-ar 44100 \
+			-af "volume=10dB" \
+			./mp3/"${mid_file%.mid}".mp3\
 			-y;
 
 		# convert wav to ogg
 		! [[ -d "./ogg" ]] && mkdir ogg;
-		ffmpeg                              \
+		ffmpeg \
 			-i ./wav/"${mid_file%.mid}".wav \
-			-af "volume=10dB"               \
-			./ogg/"${mid_file%.mid}".ogg    \
+			-af "volume=10dB" \
+			./ogg/"${mid_file%.mid}".ogg \
 			-y;
 		echo "Finished rendering ${mid_file}"
 	done
