feat: enter zathura immediately
add bash failsafe
add description
add license id
add author

diff --git a/local/bin/resume b/local/bin/resume
--- a/local/bin/resume
+++ b/local/bin/resume
@@ -1,6 +1,15 @@
 #!/usr/bin/bash
+# SPDX-License-Identifier: Unlicense
+#
+# Description:
+#     Build and display resume
+#
+# Author:
+#     elf-alchemist
+#
 
-# Build and display resume
+# Exit early, instead of failing later
+set -euo pipefail
 
 if ! command -v groff &> /dev/null; then
 	echo >&2 "Error: groff not found, please install groff."
@@ -8,10 +17,19 @@ if ! command -v groff &> /dev/null; then
 	exit 1
 fi
 
-GIT_PATH="${XDG_DATA_HOME:-"${HOME}/.local/share"}/git"
+# Modify this acording to your own organization style
+XDG_DATA_HOME="${XDG_DATA_HOME:-"${HOME}/.local/share"}"
+GIT_PATH="${XDG_DATA_HOME}/git"
 RESUME_DIR="${GIT_PATH}/elf-alchemist"
 RESUME_PDF="${RESUME_DIR}/resume.pdf"
 RESUME_MS="${RESUME_DIR}/resume.ms"
 
 groff -ms -T pdf -tle "${RESUME_MS}" > "${RESUME_PDF}"
+
+if ! command -v zathura &> /dev/null; then
+	echo >&2 "Error: zathura not found cannot auto open."
+	exit 0
+fi
+
+zathura "${RESUME_PDF}"
 
