update resume script

diff --git a/local/bin/resume b/local/bin/resume
--- a/local/bin/resume
+++ b/local/bin/resume
@@ -2,9 +2,15 @@
 
 # Build and display resume
 
+if ! [[ command -v groff &> /dev/null ]]; then
+	echo >&2 "Error: groff not found, please install groff."
+	echo >&2 "Make sure you have the ms macros installed aswell."
+	exit 1
+fi
+
 RESUME_DIR="${HOME}/code/elf-alchemist"
 RESUME_PDF="${RESUME_DIR}/resume.pdf"
 RESUME_MS="${RESUME_DIR}/resume.ms"
 
-groff -ms -T pdf "${RESUME_MS}" > "${RESUME_PDF}"
+groff -ms -T pdf -tle "${RESUME_MS}" > "${RESUME_PDF}"
 
