fix: misc minor improvement
Bash strict mode, now verbose
GIT_PATH env var
groff now uses `mspdf` option

diff --git a/local/bin/resume b/local/bin/resume
--- a/local/bin/resume
+++ b/local/bin/resume
@@ -8,8 +8,10 @@
 #     elf-alchemist
 #
 
-# Exit early, instead of failing later
-set -euo pipefail
+# Bash strict mode - Exit early, instead of failing later
+set -o errexit
+set -o nounset
+set -o pipefail
 
 if ! command -v groff &> /dev/null; then
 	echo >&2 "Error: groff not found, please install groff."
@@ -19,15 +21,16 @@ fi
 
 # Modify this acording to your own organization style
 XDG_DATA_HOME="${XDG_DATA_HOME:-"${HOME}/.local/share"}"
-GIT_PATH="${XDG_DATA_HOME}/git"
+GIT_PATH="${GIT_PATH:-"${XDG_DATA_HOME}/git"}"
 RESUME_DIR="${GIT_PATH}/elf-alchemist"
+
 RESUME_PDF="${RESUME_DIR}/resume.pdf"
 RESUME_MS="${RESUME_DIR}/resume.ms"
 
-groff -ms -T pdf -tle "${RESUME_MS}" > "${RESUME_PDF}"
+groff -m mspdf -T pdf -K utf8 -t "${RESUME_MS}" > "${RESUME_PDF}"
 
 if ! command -v zathura &> /dev/null; then
-	echo >&2 "Error: zathura not found cannot auto open."
+	echo >&2 "Error: zathura not found cannot open automatically."
 	exit 0
 fi
 
